spring:
   profiles:
      active: dev-6655
      
---
server:
   port: 6655
   
spring:
   profiles: dev-6655
   application:
      name: order-server
      
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/snack_order?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: a
   http:
      encoding:
         charset: utf-8
         force: true
         enabled: true


mybatis:
   # mapper映射文件所在路径
   mapper-locations: mapper/*Mapper.xml
   # 需要启动别名的类所在的包
   type-aliases-package: com.yc.snack.order.bean, com.yc.snack.order.dto

# hystrix超时配置
hystrix:
   command:
      # 默认超时时间为2秒，不配置的话，默认是一秒
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 2000
      # 指定方法的超时时间，这个值为要指定的降级的这个方法的方法名
      list:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 1000

feign:
   hystrix:
      enabled: true
   
# 注册到注册中心
eureka:
   client:
      service-url:
         defaultZone: http://lalala:123321@127.0.0.1:6611/eureka
         
logging:
   level:
      # com.yc.snack.order.mapper: debug
      # root: debug
      org.springframework.cloud.netflix.feign: debug